name: "Test dev container feature"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        baseImage:
        #  - debian:latest
        #  - ubuntu:latest
          - mcr.microsoft.com/devcontainers/base:ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for Radius CLI (default) against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f radcli -i ${{ matrix.baseImage }} .
        working-directory: ./ext/devcontainer

  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for radcli scenarios"
        run: devcontainer features test -f radcli -skip-autogenerated --skip-duplicated .
        working-directory: ./ext/devcontainer

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
        working-directory: ./ext/devcontainer
